@echo off

md temp
md backup

::BackUp Config
copy /y ..\stripper\maps\c1m2_streets.cfg backup\
copy /y ..\stripper\maps\c1m3_mall.cfg backup\
copy /y ..\stripper\maps\c1m4_atrium.cfg backup\
copy /y ..\stripper\maps\c2m1_highway.cfg backup\
copy /y ..\stripper\maps\c2m2_fairgrounds.cfg backup\
copy /y ..\stripper\maps\c2m3_coaster.cfg backup\
copy /y ..\stripper\maps\c2m5_concert.cfg backup\
copy /y ..\stripper\maps\c3m1_plankcountry.cfg backup\
copy /y ..\stripper\maps\c3m3_shantytown.cfg backup\
copy /y ..\stripper\maps\c3m4_plantation.cfg backup\
copy /y ..\stripper\maps\c4m1_milltown_a.cfg backup\
copy /y ..\stripper\maps\c4m2_sugarmill_a.cfg backup\
copy /y ..\stripper\maps\c4m3_sugarmill_b.cfg backup\
copy /y ..\stripper\maps\c4m4_milltown_b.cfg backup\
copy /y ..\stripper\maps\c4m5_milltown_escape.cfg backup\
copy /y ..\stripper\maps\c5m1_waterfront.cfg backup\
copy /y ..\stripper\maps\c5m2_park.cfg backup\
copy /y ..\stripper\maps\c5m3_cemetery.cfg backup\
copy /y ..\stripper\maps\c5m4_quarter.cfg backup\
copy /y ..\stripper\maps\c6m1_riverbank.cfg backup\
copy /y ..\stripper\maps\c6m2_bedlam.cfg backup\
copy /y ..\stripper\maps\c6m3_port.cfg backup\
copy /y ..\stripper\maps\c7m1_docks.cfg backup\
copy /y ..\stripper\maps\c7m2_barge.cfg backup\
copy /y ..\stripper\maps\c7m3_port.cfg backup\
copy /y ..\stripper\maps\c8m2_subway.cfg backup\
copy /y ..\stripper\maps\c8m3_sewers.cfg backup\
copy /y ..\stripper\maps\c8m4_interior.cfg backup\
copy /y ..\stripper\maps\c8m5_rooftop.cfg backup\
copy /y ..\stripper\maps\c9m1_alleys.cfg backup\
copy /y ..\stripper\maps\c9m2_lots.cfg backup\
copy /y ..\stripper\maps\c10m1_caves.cfg backup\
copy /y ..\stripper\maps\c10m2_drainage.cfg backup\
copy /y ..\stripper\maps\c10m3_ranchhouse.cfg backup\
copy /y ..\stripper\maps\c10m5_houseboat.cfg backup\
copy /y ..\stripper\maps\c11m1_greenhouse.cfg backup\
copy /y ..\stripper\maps\c11m2_offices.cfg backup\
copy /y ..\stripper\maps\c11m3_garage.cfg backup\
copy /y ..\stripper\maps\c11m4_terminal.cfg backup\
copy /y ..\stripper\maps\c11m5_runway.cfg backup\
copy /y ..\stripper\maps\c12m1_hilltop.cfg backup\
copy /y ..\stripper\maps\c12m5_cornfield.cfg backup\
copy /y ..\stripper\maps\c13m2_southpinestream.cfg backup\
copy /y ..\stripper\maps\c13m4_cutthroatcreek.cfg backup\
copy /y ..\stripper\maps\c14m1_junkyard.cfg backup\
copy /y ..\stripper\maps\c14m2_lighthouse.cfg backup\

::Replace Files
copy /y patch\c1m2_streets.cfg+..\stripper\maps\c1m2_streets.cfg temp\
copy /y patch\c1m3_mall.cfg+..\stripper\maps\c1m3_mall.cfg temp\
copy /y patch\c1m4_atrium.cfg+..\stripper\maps\c1m4_atrium.cfg temp\
copy /y patch\c2m1_highway.cfg+..\stripper\maps\c2m1_highway.cfg temp\
copy /y patch\c2m2_fairgrounds.cfg+..\stripper\maps\c2m2_fairgrounds.cfg temp\
copy /y patch\c2m3_coaster.cfg+..\stripper\maps\c2m3_coaster.cfg temp\
copy /y patch\c2m5_concert.cfg+..\stripper\maps\c2m5_concert.cfg temp\
copy /y patch\c3m1_plankcountry.cfg+..\stripper\maps\c3m1_plankcountry.cfg temp\
copy /y patch\c3m3_shantytown.cfg+..\stripper\maps\c3m3_shantytown.cfg temp\
copy /y patch\c3m4_plantation.cfg+..\stripper\maps\c3m4_plantation.cfg temp\
copy /y patch\c4m1_milltown_a.cfg+..\stripper\maps\c4m1_milltown_a.cfg temp\
copy /y patch\c4m2_sugarmill_a.cfg+..\stripper\maps\c4m2_sugarmill_a.cfg temp\
copy /y patch\c4m3_sugarmill_b.cfg+..\stripper\maps\c4m3_sugarmill_b.cfg temp\
copy /y patch\c4m4_milltown_b.cfg+..\stripper\maps\c4m4_milltown_b.cfg temp\
copy /y patch\c4m5_milltown_escape.cfg+..\stripper\maps\c4m5_milltown_escape.cfg temp\
copy /y patch\c5m1_waterfront.cfg+..\stripper\maps\c5m1_waterfront.cfg temp\
copy /y patch\c5m2_park.cfg+..\stripper\maps\c5m2_park.cfg temp\
copy /y patch\c5m3_cemetery.cfg+..\stripper\maps\c5m3_cemetery.cfg temp\
copy /y patch\c5m4_quarter.cfg+..\stripper\maps\c5m4_quarter.cfg temp\
copy /y patch\c6m1_riverbank.cfg+..\stripper\maps\c6m1_riverbank.cfg temp\
copy /y patch\c6m2_bedlam.cfg+..\stripper\maps\c6m2_bedlam.cfg temp\
copy /y patch\c6m3_port.cfg+..\stripper\maps\c6m3_port.cfg temp\
copy /y patch\c7m1_docks.cfg+..\stripper\maps\c7m1_docks.cfg temp\
copy /y patch\c7m2_barge.cfg+..\stripper\maps\c7m2_barge.cfg temp\
copy /y patch\c7m3_port.cfg+..\stripper\maps\c7m3_port.cfg temp\
copy /y patch\c8m2_subway.cfg+..\stripper\maps\c8m2_subway.cfg temp\
copy /y patch\c8m3_sewers.cfg+..\stripper\maps\c8m3_sewers.cfg temp\
copy /y patch\c8m4_interior.cfg+..\stripper\maps\c8m4_interior.cfg temp\
copy /y patch\c8m5_rooftop.cfg+..\stripper\maps\c8m5_rooftop.cfg temp\
copy /y patch\c9m1_alleys.cfg+..\stripper\maps\c9m1_alleys.cfg temp\
copy /y patch\c9m2_lots.cfg+..\stripper\maps\c9m2_lots.cfg temp\
copy /y patch\c10m1_caves.cfg+..\stripper\maps\c10m1_caves.cfg temp\
copy /y patch\c10m2_drainage.cfg+..\stripper\maps\c10m2_drainage.cfg temp\
copy /y patch\c10m3_ranchhouse.cfg+..\stripper\maps\c10m3_ranchhouse.cfg temp\
copy /y patch\c10m5_houseboat.cfg+..\stripper\maps\c10m5_houseboat.cfg temp\
copy /y patch\c11m1_greenhouse.cfg+..\stripper\maps\c11m1_greenhouse.cfg temp\
copy /y patch\c11m2_offices.cfg+..\stripper\maps\c11m2_offices.cfg temp\
copy /y patch\c11m3_garage.cfg+..\stripper\maps\c11m3_garage.cfg temp\
copy /y patch\c11m4_terminal.cfg+..\stripper\maps\c11m4_terminal.cfg temp\
copy /y patch\c11m5_runway.cfg+..\stripper\maps\c11m5_runway.cfg temp\
copy /y patch\c12m1_hilltop.cfg+..\stripper\maps\c12m1_hilltop.cfg temp\
copy /y patch\c12m5_cornfield.cfg+..\stripper\maps\c12m5_cornfield.cfg temp\
copy /y patch\c13m2_southpinestream.cfg+..\stripper\maps\c13m2_southpinestream.cfg temp\
copy /y patch\c13m4_cutthroatcreek.cfg+..\stripper\maps\c13m4_cutthroatcreek.cfg temp\
copy /y patch\c14m1_junkyard.cfg+..\stripper\maps\c14m1_junkyard.cfg temp\
copy /y patch\c14m2_lighthouse.cfg+..\stripper\maps\c14m2_lighthouse.cfg temp\
copy /y temp\* ..\stripper\maps\
rd /s /q temp\
pause